# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change Pass Menue.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChnagePsswordWindow(object):
    def setupUi(self, ChnagePsswordWindow):
        ChnagePsswordWindow.setObjectName("ChnagePsswordWindow")
        ChnagePsswordWindow.resize(501, 524)
        ChnagePsswordWindow.setStyleSheet("\n"
"")
        self.centralwidget = QtWidgets.QWidget(ChnagePsswordWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ChnagePasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChnagePasswordButton.setGeometry(QtCore.QRect(120, 390, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.ChnagePasswordButton.setFont(font)
        self.ChnagePasswordButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ChnagePasswordButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.ChnagePasswordButton.setObjectName("ChnagePasswordButton")
        self.NewPassTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.NewPassTXT.setGeometry(QtCore.QRect(260, 60, 171, 41))
        self.NewPassTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.NewPassTXT.setObjectName("NewPassTXT")
        self.CinfirmNewPassTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.CinfirmNewPassTXT.setGeometry(QtCore.QRect(260, 150, 171, 41))
        self.CinfirmNewPassTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.CinfirmNewPassTXT.setObjectName("CinfirmNewPassTXT")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 221, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 241, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.PassDoenstMatchLabel = QtWidgets.QLabel(self.centralwidget)
        self.PassDoenstMatchLabel.setGeometry(QtCore.QRect(20, 280, 471, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(24)
        self.PassDoenstMatchLabel.setFont(font)
        self.PassDoenstMatchLabel.setStyleSheet("color : red")
        self.PassDoenstMatchLabel.setText("")
        self.PassDoenstMatchLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.PassDoenstMatchLabel.setObjectName("PassDoenstMatchLabel")
        ChnagePsswordWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChnagePsswordWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 21))
        self.menubar.setObjectName("menubar")
        ChnagePsswordWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChnagePsswordWindow)
        self.statusbar.setObjectName("statusbar")
        ChnagePsswordWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChnagePsswordWindow)
        QtCore.QMetaObject.connectSlotsByName(ChnagePsswordWindow)

    def retranslateUi(self, ChnagePsswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ChnagePsswordWindow.setWindowTitle(_translate("ChnagePsswordWindow", "Change Password"))
        self.ChnagePasswordButton.setText(_translate("ChnagePsswordWindow", "Chnage Password"))
        self.label_3.setText(_translate("ChnagePsswordWindow", "New Pass"))
        self.label_4.setText(_translate("ChnagePsswordWindow", "Confirm New Pass"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChnagePsswordWindow = QtWidgets.QMainWindow()
    ui = Ui_ChnagePsswordWindow()
    ui.setupUi(ChnagePsswordWindow)
    ChnagePsswordWindow.show()
    sys.exit(app.exec_())
