# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
global account_id, account_username, account_type
from PyQt5.QtWidgets import QMessageBox

class Ui_LoginWindow(object):

    def Database(self):
        global db, cursor
        db = sqlite3.connect("R.db")
        cursor = db.cursor()
        #Staff Table

        db.execute("create table if not exists 'staff' (StaffnName TEXT, staff_username TEXT, staff_password TEXT, Email TEXT, "
                   "Salary TEXT,staff_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, StaffAddress TEXT, StaffDate TEXT)")

        db.execute("create table if not exists 'orders' (CutomerID integer, StaffID INTEGER ,"
                   "OrderId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, FoodID INTEGER , FoodPrice integer,"
                   " category TEXT, foodQunatity integer )")


        db.execute("create table if not exists 'Menue'"
                   "  (FoodId INTEGER, FoodName TEXT, FoodPrice INTEGER, FoodCategory TEXT, FoodDescription TEXT)")


        db.execute("create table if not exists 'Admin' (AdminID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL , AdminName TEXT, AdminPass TEXT)")


        db.execute("CREATE TABLE IF NOT EXISTS 'CUSTOMER'(cusID INTEGER primary key autoincrement not null ,"
                   " customerName TEXT, CUserName TEXT, CusEmail TEXT, CUstomerPass TEXT,CustomerLastName TEXT)")


        results =db.execute("Select * from 'Admin'")


        # print(results.fetchall())
        # print(len(results.fetchall())==0)

        if results.fetchone() is None:
            db.execute("insert into Admin (AdminName,AdminPass) VALUES ('admin','admin')")
            db.commit()

            print("Data inserted into admin")
        else:
            print("We have admin")
        # db.close()



    def ActivateLogin(self):
        self.Database()
        username = self.usernameTXT.text()
        pas = self.PassWordTXT.text()

        # db = sqlite3.connect("R.db")

        if username == "" or pas == "":
            qm = QMessageBox()
            qm.setText("Username and Password cannot be blank!")
            qm.exec()
        else:


            admin = db.execute("Select * from Admin where AdminName = ? AND AdminPass = ?", (str(username), str(pas)))
            admin = admin.fetchall()
            print(admin)

            cus = db.execute("Select * from CUSTOMER where CUserName = ? AND CUstomerPass = ?", (str(username), str(pas)))
            cus = cus.fetchall()
            print(cus)

            staff = db.execute("Select * from staff where staff_username = ? AND staff_password = ?", (str(username), str(pas)))
            staff = staff.fetchall()
            print(staff)


            print(len(admin))
            print(len(cus))
            print(len(staff))

            if len(admin) == 1:
                global account_id, account_username, account_typ

                account_type = "Admin"
                account_id = admin[0][0]
                account_username = username


                qm = QMessageBox()
                qm.setText("Logged in as Admin!")
                qm.exec()
                adminWindow.show()
                LoginWindow.hide()
            elif len(cus) == 1:
                qm = QMessageBox()
                qm.setText("Logged in as Customer!")
                qm.exec()

                account_type = "Customer"
                account_id = cus[0][0]
                account_username = username

                CustomerWindow.show()
                LoginWindow.hide()
            elif len(staff) == 1:
                qm = QMessageBox()
                qm.setText("Logged in as Staff!")
                qm.exec()

                account_type = "Staff"
                account_id = staff[0][0]
                account_username = username

                StaffIrderWindow.show()
                LoginWindow.hide()
            else:
                qm = QMessageBox()
                qm.setText("Wrong Password or Username!")
                qm.exec()
                self.PassWordTXT.clear()
                self.usernameTXT.clear()
            db.commit()
            self.PassWordTXT.clear()
            self.usernameTXT.clear()


    def swichtocustomerReg(self):
        LoginWindow.hide()
        RegisterWindow.show()


    def Logout(self):
        RegisterWindow.hide()
        LoginWindow.show()


    def setupUi(self, LoginWindow):
        self.Database()
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(820, 628)
        LoginWindow.setStyleSheet("background-color:rgb(145, 145, 145)")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 60, 221, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.usernameTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameTXT.setGeometry(QtCore.QRect(410, 210, 211, 41))
        self.usernameTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.usernameTXT.setObjectName("usernameTXT")
        self.PassWordTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.PassWordTXT.setGeometry(QtCore.QRect(410, 300, 211, 41))
        self.PassWordTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.PassWordTXT.setObjectName("PassWordTXT")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 190, 231, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 280, 231, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setGeometry(QtCore.QRect(440, 370, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.LoginButton.setFont(font)
        self.LoginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoginButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.LoginButton.setObjectName("LoginButton")
        self.RegisterButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegisterButton.setGeometry(QtCore.QRect(440, 470, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.RegisterButton.setFont(font)
        self.RegisterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RegisterButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.RegisterButton.setObjectName("RegisterButton")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)
        self.RegisterButton.clicked.connect(self.swichtocustomerReg)
        self.LoginButton.clicked.connect(self.ActivateLogin)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "Login"))
        self.label_2.setText(_translate("LoginWindow", "User Name:"))
        self.label_3.setText(_translate("LoginWindow", "Password:"))
        self.LoginButton.setText(_translate("LoginWindow", "Login"))
        self.RegisterButton.setText(_translate("LoginWindow", "Register"))







class Ui_RegisterWindow(object):

    def RegisterButton(self):
        db = sqlite3.connect("R.db")
        Name = self.RegNamelineEdit.text()
        Lastname = self.ReglastNamelineEdit.text()
        UserName = self.RegUserNamelineEdit.text()
        email = self.RegEmailineEdit.text()
        password = self.RegPasslineEdit.text()


        if Name == "" or Lastname == "" or UserName =="" or email =="" or password == "":
            qm = QMessageBox()
            qm.setText("Fields cannot be left Empty!")
            qm.exec()
        else:
            db.execute("""Insert into CUSTOMER 
                   (customerName,CUserName,CusEmail,CUstomerPass,CustomerLastName) VALUES (?,?,?,?,?)""",
                       (Name, UserName, email, password, Lastname))
            qm = QMessageBox()
            qm.setText("Successfully Signed up!")
            qm.exec()
            self.clearTXTs()
            self.LogoutButton()

            db.commit()
            db.close()






    def LogoutButton(self):
        RegisterWindow.hide()
        LoginWindow.show()


    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(832, 606)
        RegisterWindow.setStyleSheet("background-color: rgb(152, 152, 152)")
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RegistertheUser = QtWidgets.QPushButton(self.centralwidget)
        self.RegistertheUser.setGeometry(QtCore.QRect(590, 180, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.RegistertheUser.setFont(font)
        self.RegistertheUser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RegistertheUser.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.RegistertheUser.setObjectName("RegistertheUser")
        self.RegNamelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegNamelineEdit.setGeometry(QtCore.QRect(350, 110, 171, 41))
        self.RegNamelineEdit.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.RegNamelineEdit.setObjectName("RegNamelineEdit")
        self.ReglastNamelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ReglastNamelineEdit.setGeometry(QtCore.QRect(350, 180, 171, 41))
        self.ReglastNamelineEdit.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.ReglastNamelineEdit.setObjectName("ReglastNamelineEdit")
        self.RegUserNamelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegUserNamelineEdit.setGeometry(QtCore.QRect(350, 250, 171, 41))
        self.RegUserNamelineEdit.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.RegUserNamelineEdit.setObjectName("RegUserNamelineEdit")
        self.RegEmailineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegEmailineEdit.setGeometry(QtCore.QRect(350, 310, 171, 41))
        self.RegEmailineEdit.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.RegEmailineEdit.setObjectName("RegEmailineEdit")
        self.RegPasslineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegPasslineEdit.setGeometry(QtCore.QRect(350, 380, 171, 41))
        self.RegPasslineEdit.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.RegPasslineEdit.setObjectName("RegPasslineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 221, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 180, 221, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 250, 231, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 300, 231, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 370, 231, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(230, 10, 441, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.ClearButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton.setGeometry(QtCore.QRect(590, 270, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.ClearButton.setFont(font)
        self.ClearButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ClearButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.ClearButton.setObjectName("ClearButton")
        self.BackToLogin = QtWidgets.QPushButton(self.centralwidget)
        self.BackToLogin.setGeometry(QtCore.QRect(590, 360, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.BackToLogin.setFont(font)
        self.BackToLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BackToLogin.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.BackToLogin.setObjectName("BackToLogin")
        RegisterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegisterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 21))
        self.menubar.setObjectName("menubar")
        RegisterWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegisterWindow)
        self.statusbar.setObjectName("statusbar")
        RegisterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)
        self.BackToLogin.clicked.connect(Ui_LoginWindow.Logout)
        self.ClearButton.clicked.connect(self.clearTXTs)
        self.RegistertheUser.clicked.connect(self.RegisterButton)
        self.BackToLogin.clicked.connect(self.LogoutButton)

    def clearTXTs(self):
        self.RegNamelineEdit.clear()
        self.RegUserNamelineEdit.clear()
        self.ReglastNamelineEdit.clear()
        self.RegEmailineEdit.clear()
        self.RegPasslineEdit.clear()


    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "MainWindow"))
        self.RegistertheUser.setText(_translate("RegisterWindow", "Register"))
        self.label_2.setText(_translate("RegisterWindow", "Name:"))
        self.label_3.setText(_translate("RegisterWindow", "Last name:"))
        self.label_4.setText(_translate("RegisterWindow", "User Name:"))
        self.label_5.setText(_translate("RegisterWindow", "Email:"))
        self.label_6.setText(_translate("RegisterWindow", "Password:"))
        self.label_7.setText(_translate("RegisterWindow", "Customer Registration"))
        self.ClearButton.setText(_translate("RegisterWindow", "Clear"))
        self.BackToLogin.setText(_translate("RegisterWindow", "Back"))











class Ui_CustomerWindow(object):
    def setupUi(self, CustomerWindow):
        CustomerWindow.setObjectName("CustomerWindow")
        CustomerWindow.setEnabled(True)
        CustomerWindow.resize(1032, 789)
        self.centralwidget = QtWidgets.QWidget(CustomerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1021, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(135, 135, 135)")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 70, 211, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 390, 221, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.CustomerFoodTable = QtWidgets.QTableWidget(self.centralwidget)
        self.CustomerFoodTable.setEnabled(True)
        self.CustomerFoodTable.setGeometry(QtCore.QRect(320, 80, 401, 271))
        self.CustomerFoodTable.setObjectName("CustomerFoodTable")
        self.CustomerFoodTable.setColumnCount(4)
        self.CustomerFoodTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.CustomerFoodTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CustomerFoodTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CustomerFoodTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CustomerFoodTable.setHorizontalHeaderItem(3, item)
        self.CustomerOrdeTable = QtWidgets.QTableWidget(self.centralwidget)
        self.CustomerOrdeTable.setGeometry(QtCore.QRect(320, 390, 601, 271))
        self.CustomerOrdeTable.setObjectName("CustomerOrdeTable")
        self.CustomerOrdeTable.setColumnCount(6)
        self.CustomerOrdeTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.CustomerOrdeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CustomerOrdeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CustomerOrdeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CustomerOrdeTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CustomerOrdeTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CustomerOrdeTable.setHorizontalHeaderItem(5, item)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 350, 901, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.AddorderButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddorderButton.setGeometry(QtCore.QRect(100, 470, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.AddorderButton.setFont(font)
        self.AddorderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddorderButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.AddorderButton.setObjectName("AddorderButton")
        self.DeleteOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteOrderButton.setGeometry(QtCore.QRect(100, 530, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.DeleteOrderButton.setFont(font)
        self.DeleteOrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DeleteOrderButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.DeleteOrderButton.setObjectName("DeleteOrderButton")
        self.ConfirmOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmOrderButton.setGeometry(QtCore.QRect(410, 680, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.ConfirmOrderButton.setFont(font)
        self.ConfirmOrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ConfirmOrderButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.ConfirmOrderButton.setObjectName("ConfirmOrderButton")
        self.LogoutOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogoutOrderButton.setGeometry(QtCore.QRect(20, 680, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.LogoutOrderButton.setFont(font)
        self.LogoutOrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogoutOrderButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.LogoutOrderButton.setObjectName("LogoutOrderButton")
        self.PrintInvoiceButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrintInvoiceButton.setGeometry(QtCore.QRect(610, 680, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.PrintInvoiceButton.setFont(font)
        self.PrintInvoiceButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PrintInvoiceButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.PrintInvoiceButton.setObjectName("PrintInvoiceButton")
        CustomerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CustomerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 21))
        self.menubar.setObjectName("menubar")
        CustomerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CustomerWindow)
        self.statusbar.setObjectName("statusbar")
        CustomerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CustomerWindow)
        QtCore.QMetaObject.connectSlotsByName(CustomerWindow)

    def retranslateUi(self, CustomerWindow):
        _translate = QtCore.QCoreApplication.translate
        CustomerWindow.setWindowTitle(_translate("CustomerWindow", "MainWindow"))
        self.label.setText(_translate("CustomerWindow", "Customer"))
        self.label_2.setText(_translate("CustomerWindow", "Menu"))
        self.label_3.setText(_translate("CustomerWindow", "Your Order"))
        item = self.CustomerFoodTable.horizontalHeaderItem(0)
        item.setText(_translate("CustomerWindow", "Food ID"))
        item = self.CustomerFoodTable.horizontalHeaderItem(1)
        item.setText(_translate("CustomerWindow", "Food Name"))
        item = self.CustomerFoodTable.horizontalHeaderItem(2)
        item.setText(_translate("CustomerWindow", "Food Price"))
        item = self.CustomerFoodTable.horizontalHeaderItem(3)
        item.setText(_translate("CustomerWindow", "Category"))
        item = self.CustomerOrdeTable.horizontalHeaderItem(0)
        item.setText(_translate("CustomerWindow", "Food ID"))
        item = self.CustomerOrdeTable.horizontalHeaderItem(1)
        item.setText(_translate("CustomerWindow", "Food Name"))
        item = self.CustomerOrdeTable.horizontalHeaderItem(2)
        item.setText(_translate("CustomerWindow", "Food Price"))
        item = self.CustomerOrdeTable.horizontalHeaderItem(3)
        item.setText(_translate("CustomerWindow", "Category"))
        item = self.CustomerOrdeTable.horizontalHeaderItem(4)
        item.setText(_translate("CustomerWindow", "Quantity"))
        item = self.CustomerOrdeTable.horizontalHeaderItem(5)
        item.setText(_translate("CustomerWindow", "Total Price"))
        self.AddorderButton.setText(_translate("CustomerWindow", "Add Order"))
        self.DeleteOrderButton.setText(_translate("CustomerWindow", "Delete Order"))
        self.ConfirmOrderButton.setText(_translate("CustomerWindow", "Confirm Order"))
        self.LogoutOrderButton.setText(_translate("CustomerWindow", "Logout"))
        self.PrintInvoiceButton.setText(_translate("CustomerWindow", "Print Invoice"))





#related to admin















class Ui_adminWindow(object):

    def forlupdatethestaff(self):
        db= sqlite3.connect("R.db")
        row = self.staffTable.selectedItems()
        mylsit = []
        for y in row:
            mylsit.append(y.text())
            id = mylsit[0]
        result = db.execute("SELECT StaffnName, staff_username, staff_password, Email, Salary, StaffAddress, StaffDate FROM staff where staff_id = ?", (id,))
        result= result.fetchall()
        Sname = result[0][0]
        staffUserName = result[0][1]
        staffpassword = result[0][2]
        staffeamil = result[0][3]
        staffSalary = result[0][4]
        staffaddress = result[0][5]
        staffstartDate = result[0][6]
        # print(Sname,staffUserName,staffpassword,staffeamil,staffSalary,staffaddress,staffstartDate)

        return Sname, staffUserName, staffpassword , staffeamil, staffSalary, staffaddress, staffstartDate

        # print("results for update window: ",result)
        # qm = QMessageBox()
        # qm.setText("Row deleted!")
        # qm.exec()



    def showstaffTable(self):
        db = sqlite3.connect("R.db")
        result = db.execute(" SELECT staff_id,StaffnName,staff_username,staff_password,Email,Salary from staff")
        result = result.fetchall()

        for rowNum, rowData in enumerate(result):
            # print(rowNum, rowData)
            self.staffTable.setRowCount(rowNum + 1)
            for colNum, colData in enumerate(rowData):
                # print(colNum, colData)

                self.staffTable.setItem(rowNum, colNum, QtWidgets.QTableWidgetItem(str(colData)))

        db.commit()
        db.close()

    def logout(self):
        adminWindow.hide()
        LoginWindow.show()

    def ActivateAddStaffButton(self):
        AddStaffWIndow.show()
        # adminWindow.hide()



    def ActivateDeleteButton(self):
        db = sqlite3.connect("R.db")
        row = self.staffTable.selectedItems()
        mylsit = []
        for y in row:
            mylsit.append(y.text())
            id = mylsit[0]

        print("selected ID number is: ",id)
        print(type(row))

        if not self.staffTable.selectedItems():
            qm = QMessageBox()
            qm.setText("Select a field to Delete!")
            qm.exec()
        else:
            db.execute("DELETE FROM staff WHERE staff_id = ?",(id,))
            qm = QMessageBox()
            qm.setText("Row deleted!")
            qm.exec()


            result = db.execute(" SELECT staff_id,StaffnName,staff_username,staff_password,Email,Salary from staff")
            result = result.fetchall()
            self.staffTable.setRowCount(0)

            for rowNum, rowData in enumerate(result):
                # print(rowNum, rowData)
                self.staffTable.setRowCount(rowNum + 1)
                for colNum, colData in enumerate(rowData):
                    # print(colNum, colData)

                    self.staffTable.setItem(rowNum, colNum, QtWidgets.QTableWidgetItem(str(colData)))


        db.commit()
        db.close()
    def switchtstaffupdateWindow(self):

        UpdateStaffWindow.show()














            # db.execute(
            #     # "create table if not exists 'staff' (StaffnName TEXT, staff_username TEXT, staff_password TEXT, Email TEXT, "
            #     # "Salary TEXT,staff_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, StaffAddress TEXT, StaffDate TEXT)")
            #


    def setupUi(self, adminWindow):

        adminWindow.setObjectName("adminWindow")
        adminWindow.resize(935, 663)
        self.centralwidget = QtWidgets.QWidget(adminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 921, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.staffTable = QtWidgets.QTableWidget(self.centralwidget)
        self.staffTable.setGeometry(QtCore.QRect(0, 120, 601, 381))
        self.staffTable.setObjectName("staffTable")
        self.staffTable.setColumnCount(7)
        self.staffTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(6, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 231, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.AddStaffButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddStaffButton.setGeometry(QtCore.QRect(650, 120, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.AddStaffButton.setFont(font)
        self.AddStaffButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddStaffButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.AddStaffButton.setObjectName("AddStaffButton")
        self.DeleteStaffButotn = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteStaffButotn.setGeometry(QtCore.QRect(650, 180, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.DeleteStaffButotn.setFont(font)
        self.DeleteStaffButotn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DeleteStaffButotn.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.DeleteStaffButotn.setObjectName("DeleteStaffButotn")
        self.UpdateStafffButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateStafffButton.setGeometry(QtCore.QRect(650, 240, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.UpdateStafffButton.setFont(font)
        self.UpdateStafffButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UpdateStafffButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.UpdateStafffButton.setObjectName("UpdateStafffButton")
        self.LogoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogoutButton.setGeometry(QtCore.QRect(40, 520, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.LogoutButton.setFont(font)
        self.LogoutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogoutButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.LogoutButton.setObjectName("LogoutButton")
        self.FoodMenuButton = QtWidgets.QPushButton(self.centralwidget)
        self.FoodMenuButton.setGeometry(QtCore.QRect(650, 300, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.FoodMenuButton.setFont(font)
        self.FoodMenuButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FoodMenuButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.FoodMenuButton.setObjectName("FoodMenuButton")
        self.StatisticsButton = QtWidgets.QPushButton(self.centralwidget)
        self.StatisticsButton.setGeometry(QtCore.QRect(650, 360, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.StatisticsButton.setFont(font)
        self.StatisticsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StatisticsButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.StatisticsButton.setObjectName("StatisticsButton")
        self.OrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.OrderButton.setGeometry(QtCore.QRect(650, 420, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.OrderButton.setFont(font)
        self.OrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OrderButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.OrderButton.setObjectName("OrderButton")
        self.VisitProfile = QtWidgets.QPushButton(self.centralwidget)
        self.VisitProfile.setGeometry(QtCore.QRect(650, 480, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.VisitProfile.setFont(font)
        self.VisitProfile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VisitProfile.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.VisitProfile.setObjectName("VisitProfile")
        self.LoadDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadDataButton.setGeometry(QtCore.QRect(650, 540, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.LoadDataButton.setFont(font)
        self.LoadDataButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoadDataButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.LoadDataButton.setObjectName("LoadDataButton")
        adminWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(adminWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 21))
        self.menubar.setObjectName("menubar")
        adminWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(adminWindow)
        self.statusbar.setObjectName("statusbar")
        adminWindow.setStatusBar(self.statusbar)
        self.LogoutButton.clicked.connect(self.logout)
        self.LoadDataButton.clicked.connect(self.showstaffTable)
        self.retranslateUi(adminWindow)
        QtCore.QMetaObject.connectSlotsByName(adminWindow)
        self.AddStaffButton.clicked.connect(self.ActivateAddStaffButton)
        self.DeleteStaffButotn.clicked.connect(self.ActivateDeleteButton)
        self.UpdateStafffButton.clicked.connect(self.switchtstaffupdateWindow)


        db = sqlite3.connect("R.db")
        result = db.execute(" SELECT staff_id,StaffnName,staff_username,staff_password,Email,Salary from staff")
        result = result.fetchall()

        for rowNum, rowData in enumerate(result):
            # print(rowNum, rowData)
            self.staffTable.setRowCount(rowNum + 1)
            for colNum, colData in enumerate(rowData):
                # print(colNum, colData)

                self.staffTable.setItem(rowNum, colNum, QtWidgets.QTableWidgetItem(str(colData)))

        db.commit()
        db.close()



    def retranslateUi(self, adminWindow):
        _translate = QtCore.QCoreApplication.translate
        adminWindow.setWindowTitle(_translate("adminWindow", "MainWindow"))
        self.label.setText(_translate("adminWindow", "Administrator View"))
        item = self.staffTable.horizontalHeaderItem(0)
        item.setText(_translate("adminWindow", "ID"))
        item = self.staffTable.horizontalHeaderItem(1)
        item.setText(_translate("adminWindow", "Name"))
        item = self.staffTable.horizontalHeaderItem(2)
        item.setText(_translate("adminWindow", "User Name"))
        item = self.staffTable.horizontalHeaderItem(3)
        item.setText(_translate("adminWindow", "Password"))
        item = self.staffTable.horizontalHeaderItem(4)
        item.setText(_translate("adminWindow", "Email"))
        item = self.staffTable.horizontalHeaderItem(5)
        item.setText(_translate("adminWindow", "Salary"))
        self.label_2.setText(_translate("adminWindow", "Staff Table"))
        self.AddStaffButton.setText(_translate("adminWindow", "Add Staff"))
        self.DeleteStaffButotn.setText(_translate("adminWindow", "Delete Staff"))
        self.UpdateStafffButton.setText(_translate("adminWindow", "Update Staff"))
        self.LogoutButton.setText(_translate("adminWindow", "Logout"))
        self.FoodMenuButton.setText(_translate("adminWindow", "Foood Menu"))
        self.StatisticsButton.setText(_translate("adminWindow", "Statistics"))
        self.OrderButton.setText(_translate("adminWindow", "Orders"))
        self.VisitProfile.setText(_translate("adminWindow", "Visit Profile"))
        self.LoadDataButton.setText(_translate("adminWindow", "Load Data"))





class Ui_AddStaffWIndow(object):




    def clearTXT(self):
        self.AddStaffname.clear()
        self.AddStaffuserName.clear()
        self.AddStaffEmai.clear()
        self.ADDAddressStaff.clear()
        self.AddStaffSalary.clear()
        self.AddStartDateStaff.clear()
        self.AddStaffpass.clear()

    def ActivateRegisterButton(self):
        db = sqlite3.connect("R.db")

        Name = self.AddStaffname.text()
        username = self.AddStaffuserName.text()
        password = self.AddStaffpass.text()
        eemail = self.AddStaffEmai.text()
        salary = self.AddStaffSalary.text()
        Addressw = self.ADDAddressStaff.text()
        startDate = self.AddStartDateStaff.text()

        if Name =="" or username =="" or password =="" or eemail == "" or salary =="" or Addressw =="" or startDate =="":
            qm = QMessageBox()
            qm.setText("Fields cannot be left blank!")
            qm.exec()
        else:
            db.execute(""" Insert into staff (StaffnName,staff_username,staff_password,Email,Salary,StaffAddress,StaffDate)
                  VALUES (?,?,?,?,?,?,?)""", (Name, username, password, eemail, salary, Addressw, startDate))
            db.commit()
            db.close()
            self.clearTXT()

            qm = QMessageBox()
            qm.setText("Staff Added!")
            qm.exec()








    def setupUi(self, AddStaffWIndow):
        AddStaffWIndow.setObjectName("AddStaffWIndow")
        AddStaffWIndow.resize(601, 743)
        self.centralwidget = QtWidgets.QWidget(AddStaffWIndow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -10, 601, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.AddStaffname = QtWidgets.QLineEdit(self.centralwidget)
        self.AddStaffname.setGeometry(QtCore.QRect(290, 70, 171, 41))
        self.AddStaffname.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.AddStaffname.setObjectName("AddStaffname")
        self.AddStaffuserName = QtWidgets.QLineEdit(self.centralwidget)
        self.AddStaffuserName.setGeometry(QtCore.QRect(290, 130, 171, 41))
        self.AddStaffuserName.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.AddStaffuserName.setObjectName("AddStaffuserName")
        self.AddStaffpass = QtWidgets.QLineEdit(self.centralwidget)
        self.AddStaffpass.setGeometry(QtCore.QRect(290, 190, 171, 41))
        self.AddStaffpass.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.AddStaffpass.setObjectName("AddStaffpass")
        self.AddStaffEmai = QtWidgets.QLineEdit(self.centralwidget)
        self.AddStaffEmai.setGeometry(QtCore.QRect(290, 250, 171, 41))
        self.AddStaffEmai.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.AddStaffEmai.setObjectName("AddStaffEmai")
        self.AddStaffSalary = QtWidgets.QLineEdit(self.centralwidget)
        self.AddStaffSalary.setGeometry(QtCore.QRect(290, 310, 171, 41))
        self.AddStaffSalary.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.AddStaffSalary.setObjectName("AddStaffSalary")
        self.AddStaffButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddStaffButton.setGeometry(QtCore.QRect(200, 610, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.AddStaffButton.setFont(font)
        self.AddStaffButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddStaffButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.AddStaffButton.setObjectName("AddStaffButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 70, 221, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 221, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 190, 221, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 240, 221, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 310, 221, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 380, 221, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(80, 470, 221, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.ADDAddressStaff = QtWidgets.QLineEdit(self.centralwidget)
        self.ADDAddressStaff.setGeometry(QtCore.QRect(290, 390, 171, 41))
        self.ADDAddressStaff.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.ADDAddressStaff.setObjectName("ADDAddressStaff")
        self.AddStartDateStaff = QtWidgets.QLineEdit(self.centralwidget)
        self.AddStartDateStaff.setGeometry(QtCore.QRect(290, 480, 171, 41))
        self.AddStartDateStaff.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.AddStartDateStaff.setObjectName("AddStartDateStaff")
        AddStaffWIndow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddStaffWIndow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 21))
        self.menubar.setObjectName("menubar")
        AddStaffWIndow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddStaffWIndow)
        self.statusbar.setObjectName("statusbar")
        AddStaffWIndow.setStatusBar(self.statusbar)
        self.AddStaffButton.clicked.connect(self.ActivateRegisterButton)

        self.retranslateUi(AddStaffWIndow)
        QtCore.QMetaObject.connectSlotsByName(AddStaffWIndow)

    def retranslateUi(self, AddStaffWIndow):
        _translate = QtCore.QCoreApplication.translate
        AddStaffWIndow.setWindowTitle(_translate("AddStaffWIndow", "MainWindow"))
        self.label_2.setText(_translate("AddStaffWIndow", "Add Staff"))
        self.AddStaffButton.setText(_translate("AddStaffWIndow", "Register"))
        self.label_3.setText(_translate("AddStaffWIndow", "Name:"))
        self.label_4.setText(_translate("AddStaffWIndow", "User"))
        self.label_5.setText(_translate("AddStaffWIndow", "password"))
        self.label_6.setText(_translate("AddStaffWIndow", "Email"))
        self.label_7.setText(_translate("AddStaffWIndow", "Salary"))
        self.label_9.setText(_translate("AddStaffWIndow", "Address"))
        self.label_10.setText(_translate("AddStaffWIndow", "Start Date"))




class Ui_OrdersWindow(object):

    def setupUi(self, OrdersWindow):
        OrdersWindow.setObjectName("OrdersWindow")
        OrdersWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(OrdersWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OrderTable = QtWidgets.QTableWidget(self.centralwidget)
        self.OrderTable.setGeometry(QtCore.QRect(180, 110, 501, 321))
        self.OrderTable.setObjectName("OrderTable")
        self.OrderTable.setColumnCount(7)
        self.OrderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(6, item)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 10, 441, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.DeleteOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteOrderButton.setGeometry(QtCore.QRect(340, 460, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.DeleteOrderButton.setFont(font)
        self.DeleteOrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DeleteOrderButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.DeleteOrderButton.setObjectName("DeleteOrderButton")
        OrdersWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OrdersWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        OrdersWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OrdersWindow)
        self.statusbar.setObjectName("statusbar")
        OrdersWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OrdersWindow)
        QtCore.QMetaObject.connectSlotsByName(OrdersWindow)

    def retranslateUi(self, OrdersWindow):
        _translate = QtCore.QCoreApplication.translate
        OrdersWindow.setWindowTitle(_translate("OrdersWindow", "MainWindow"))
        item = self.OrderTable.horizontalHeaderItem(0)
        item.setText(_translate("OrdersWindow", "Order ID"))
        item = self.OrderTable.horizontalHeaderItem(1)
        item.setText(_translate("OrdersWindow", "Item Name"))
        item = self.OrderTable.horizontalHeaderItem(2)
        item.setText(_translate("OrdersWindow", "Item Price"))
        item = self.OrderTable.horizontalHeaderItem(3)
        item.setText(_translate("OrdersWindow", "Order Status"))
        item = self.OrderTable.horizontalHeaderItem(4)
        item.setText(_translate("OrdersWindow", "Total Price"))
        self.label_7.setText(_translate("OrdersWindow", "Orders"))
        self.DeleteOrderButton.setText(_translate("OrdersWindow", "Delete Order"))













class Ui_FoodsWindow(object):
    def setupUi(self, FoodsWindow):
        FoodsWindow.setObjectName("FoodsWindow")
        FoodsWindow.resize(1072, 589)
        self.centralwidget = QtWidgets.QWidget(FoodsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FoodTable = QtWidgets.QTableWidget(self.centralwidget)
        self.FoodTable.setGeometry(QtCore.QRect(30, 80, 411, 401))
        self.FoodTable.setObjectName("FoodTable")
        self.FoodTable.setColumnCount(4)
        self.FoodTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.FoodTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.FoodTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.FoodTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.FoodTable.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1051, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(170, 170, 127)")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.AdFoodButton = QtWidgets.QPushButton(self.centralwidget)
        self.AdFoodButton.setGeometry(QtCore.QRect(860, 350, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.AdFoodButton.setFont(font)
        self.AdFoodButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AdFoodButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.AdFoodButton.setObjectName("AdFoodButton")
        self.LogoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogoutButton.setGeometry(QtCore.QRect(30, 500, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.LogoutButton.setFont(font)
        self.LogoutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogoutButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.LogoutButton.setObjectName("LogoutButton")
        self.UpdateFoodButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateFoodButton.setGeometry(QtCore.QRect(460, 240, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.UpdateFoodButton.setFont(font)
        self.UpdateFoodButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UpdateFoodButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.UpdateFoodButton.setObjectName("UpdateFoodButton")
        self.DelteFoodButton = QtWidgets.QPushButton(self.centralwidget)
        self.DelteFoodButton.setGeometry(QtCore.QRect(460, 170, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.DelteFoodButton.setFont(font)
        self.DelteFoodButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DelteFoodButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.DelteFoodButton.setObjectName("DelteFoodButton")
        self.LoadFooddButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadFooddButton.setGeometry(QtCore.QRect(460, 100, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.LoadFooddButton.setFont(font)
        self.LoadFooddButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoadFooddButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.LoadFooddButton.setObjectName("LoadFooddButton")
        self.FoodAddIDTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.FoodAddIDTXT.setGeometry(QtCore.QRect(830, 80, 211, 41))
        self.FoodAddIDTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.FoodAddIDTXT.setObjectName("FoodAddIDTXT")
        self.FoodAddNameTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.FoodAddNameTXT.setGeometry(QtCore.QRect(830, 140, 211, 41))
        self.FoodAddNameTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.FoodAddNameTXT.setObjectName("FoodAddNameTXT")
        self.FoodAddPricetXT = QtWidgets.QLineEdit(self.centralwidget)
        self.FoodAddPricetXT.setGeometry(QtCore.QRect(830, 200, 211, 41))
        self.FoodAddPricetXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.FoodAddPricetXT.setObjectName("FoodAddPricetXT")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(660, 80, 161, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 130, 181, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 190, 181, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.FoodCategoriesBox = QtWidgets.QComboBox(self.centralwidget)
        self.FoodCategoriesBox.setGeometry(QtCore.QRect(830, 261, 211, 41))
        self.FoodCategoriesBox.setStyleSheet("background-color:rgb(159, 159, 159)\n"
"")
        self.FoodCategoriesBox.setObjectName("FoodCategoriesBox")
        self.FoodCategoriesBox.addItem("")
        self.FoodCategoriesBox.addItem("")
        self.FoodCategoriesBox.addItem("")
        self.FoodCategoriesBox.addItem("")
        self.FoodCategoriesBox.addItem("")
        FoodsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FoodsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 21))
        self.menubar.setObjectName("menubar")
        FoodsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FoodsWindow)
        self.statusbar.setObjectName("statusbar")
        FoodsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FoodsWindow)
        QtCore.QMetaObject.connectSlotsByName(FoodsWindow)

    def retranslateUi(self, FoodsWindow):
        _translate = QtCore.QCoreApplication.translate
        FoodsWindow.setWindowTitle(_translate("FoodsWindow", "MainWindow"))
        item = self.FoodTable.horizontalHeaderItem(0)
        item.setText(_translate("FoodsWindow", "Food ID"))
        item = self.FoodTable.horizontalHeaderItem(1)
        item.setText(_translate("FoodsWindow", "Food Name"))
        item = self.FoodTable.horizontalHeaderItem(2)
        item.setText(_translate("FoodsWindow", "Food Price"))
        item = self.FoodTable.horizontalHeaderItem(3)
        item.setText(_translate("FoodsWindow", "Category"))
        self.label.setText(_translate("FoodsWindow", "Food"))
        self.AdFoodButton.setText(_translate("FoodsWindow", "Add Food"))
        self.LogoutButton.setText(_translate("FoodsWindow", "Logout"))
        self.UpdateFoodButton.setText(_translate("FoodsWindow", "Update Product"))
        self.DelteFoodButton.setText(_translate("FoodsWindow", "Delete Product"))
        self.LoadFooddButton.setText(_translate("FoodsWindow", "Load"))
        self.label_2.setText(_translate("FoodsWindow", "Food ID"))
        self.label_3.setText(_translate("FoodsWindow", "Name"))
        self.label_4.setText(_translate("FoodsWindow", "Price"))
        self.FoodCategoriesBox.setItemText(0, _translate("FoodsWindow", "Main Course"))
        self.FoodCategoriesBox.setItemText(1, _translate("FoodsWindow", "Desserts"))
        self.FoodCategoriesBox.setItemText(2, _translate("FoodsWindow", "Apptizers"))
        self.FoodCategoriesBox.setItemText(3, _translate("FoodsWindow", "Drinks"))
        self.FoodCategoriesBox.setItemText(4, _translate("FoodsWindow", "Extra Services"))








class Ui_StaffIrderWindow(object):
    def logout(self):
        StaffIrderWindow.hide()
        LoginWindow.show()

    def setupUi(self, StaffIrderWindow):
        StaffIrderWindow.setObjectName("StaffIrderWindow")
        StaffIrderWindow.resize(800, 690)
        self.centralwidget = QtWidgets.QWidget(StaffIrderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 791, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(135, 135, 135)")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.StaffOrderTable = QtWidgets.QTableWidget(self.centralwidget)
        self.StaffOrderTable.setGeometry(QtCore.QRect(320, 80, 431, 321))
        self.StaffOrderTable.setObjectName("StaffOrderTable")
        self.StaffOrderTable.setColumnCount(6)
        self.StaffOrderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.StaffOrderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.StaffOrderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.StaffOrderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.StaffOrderTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.StaffOrderTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.StaffOrderTable.setHorizontalHeaderItem(5, item)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 311, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.ConfirmOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmOrderButton.setGeometry(QtCore.QRect(90, 450, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.ConfirmOrderButton.setFont(font)
        self.ConfirmOrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ConfirmOrderButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.ConfirmOrderButton.setObjectName("ConfirmOrderButton")
        self.RejectOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.RejectOrderButton.setGeometry(QtCore.QRect(340, 450, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.RejectOrderButton.setFont(font)
        self.RejectOrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RejectOrderButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.RejectOrderButton.setObjectName("RejectOrderButton")
        self.NextOrdewrButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextOrdewrButton.setGeometry(QtCore.QRect(570, 450, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.NextOrdewrButton.setFont(font)
        self.NextOrdewrButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NextOrdewrButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.NextOrdewrButton.setObjectName("NextOrdewrButton")
        self.LogoutOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogoutOrderButton.setGeometry(QtCore.QRect(20, 580, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.LogoutOrderButton.setFont(font)
        self.LogoutOrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogoutOrderButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.LogoutOrderButton.setObjectName("LogoutOrderButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 300, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.CustomerIdLabel = QtWidgets.QLabel(self.centralwidget)
        self.CustomerIdLabel.setGeometry(QtCore.QRect(120, 150, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.CustomerIdLabel.setFont(font)
        self.CustomerIdLabel.setText("")
        self.CustomerIdLabel.setObjectName("CustomerIdLabel")
        self.CustomerNameLable = QtWidgets.QLabel(self.centralwidget)
        self.CustomerNameLable.setGeometry(QtCore.QRect(140, 230, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.CustomerNameLable.setFont(font)
        self.CustomerNameLable.setText("")
        self.CustomerNameLable.setObjectName("CustomerNameLable")
        self.CustomerOrderIDLabel = QtWidgets.QLabel(self.centralwidget)
        self.CustomerOrderIDLabel.setGeometry(QtCore.QRect(150, 300, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.CustomerOrderIDLabel.setFont(font)
        self.CustomerOrderIDLabel.setText("")
        self.CustomerOrderIDLabel.setObjectName("CustomerOrderIDLabel")
        StaffIrderWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StaffIrderWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        StaffIrderWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StaffIrderWindow)
        self.statusbar.setObjectName("statusbar")
        StaffIrderWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StaffIrderWindow)
        QtCore.QMetaObject.connectSlotsByName(StaffIrderWindow)
        self.LogoutOrderButton.clicked.connect(self.logout)

    def retranslateUi(self, StaffIrderWindow):
        _translate = QtCore.QCoreApplication.translate
        StaffIrderWindow.setWindowTitle(_translate("StaffIrderWindow", "MainWindow"))
        self.label.setText(_translate("StaffIrderWindow", "Staff"))
        item = self.StaffOrderTable.horizontalHeaderItem(0)
        item.setText(_translate("StaffIrderWindow", "Order ID"))
        item = self.StaffOrderTable.horizontalHeaderItem(1)
        item.setText(_translate("StaffIrderWindow", "Item Name"))
        item = self.StaffOrderTable.horizontalHeaderItem(2)
        item.setText(_translate("StaffIrderWindow", "Item Price"))
        item = self.StaffOrderTable.horizontalHeaderItem(3)
        item.setText(_translate("StaffIrderWindow", "Quantity"))
        self.label_7.setText(_translate("StaffIrderWindow", "Orders"))
        self.ConfirmOrderButton.setText(_translate("StaffIrderWindow", "Confirm Order"))
        self.RejectOrderButton.setText(_translate("StaffIrderWindow", "Reject Order"))
        self.NextOrdewrButton.setText(_translate("StaffIrderWindow", "Next Order"))
        self.LogoutOrderButton.setText(_translate("StaffIrderWindow", "LogOut"))
        self.label_2.setText(_translate("StaffIrderWindow", "Cutomer\'s ID:"))
        self.label_3.setText(_translate("StaffIrderWindow", "Cutomer\'s Name:"))
        self.label_4.setText(_translate("StaffIrderWindow", "Cutomer\'s Order ID"))




class Ui_UpdateStaffWindow(object):




    def setupUi(self, UpdateStaffWindow):
        UpdateStaffWindow.setObjectName("UpdateStaffWindow")
        UpdateStaffWindow.resize(655, 769)
        self.centralwidget = QtWidgets.QWidget(UpdateStaffWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UpdateUserNameTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.UpdateUserNameTXT.setGeometry(QtCore.QRect(360, 180, 171, 41))
        self.UpdateUserNameTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.UpdateUserNameTXT.setObjectName("UpdateUserNameTXT")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 290, 221, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 360, 221, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.Updatethestaff = QtWidgets.QPushButton(self.centralwidget)
        self.Updatethestaff.setGeometry(QtCore.QRect(250, 670, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.Updatethestaff.setFont(font)
        self.Updatethestaff.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Updatethestaff.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.Updatethestaff.setObjectName("Updatethestaff")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 170, 221, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 110, 221, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.UpDateStafTXt = QtWidgets.QLineEdit(self.centralwidget)
        self.UpDateStafTXt.setGeometry(QtCore.QRect(360, 110, 171, 41))
        self.UpDateStafTXt.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.UpDateStafTXt.setObjectName("UpDateStafTXt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 240, 221, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.UpdateEmailTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.UpdateEmailTXT.setGeometry(QtCore.QRect(360, 300, 171, 41))
        self.UpdateEmailTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.UpdateEmailTXT.setObjectName("UpdateEmailTXT")
        self.updateSalaryTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.updateSalaryTXT.setGeometry(QtCore.QRect(360, 370, 171, 41))
        self.updateSalaryTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.updateSalaryTXT.setObjectName("updateSalaryTXT")
        self.UpdatePassTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.UpdatePassTXT.setGeometry(QtCore.QRect(360, 240, 171, 41))
        self.UpdatePassTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.UpdatePassTXT.setObjectName("UpdatePassTXT")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(140, 20, 441, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(130, 450, 221, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(140, 530, 221, 51))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName("label_13")
        self.updateAddressTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.updateAddressTXT.setGeometry(QtCore.QRect(360, 460, 171, 41))
        self.updateAddressTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.updateAddressTXT.setObjectName("updateAddressTXT")
        self.UpdateStartDateTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.UpdateStartDateTXT.setGeometry(QtCore.QRect(360, 540, 171, 41))
        self.UpdateStartDateTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.UpdateStartDateTXT.setObjectName("UpdateStartDateTXT")
        UpdateStaffWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UpdateStaffWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 655, 21))
        self.menubar.setObjectName("menubar")
        UpdateStaffWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UpdateStaffWindow)
        self.statusbar.setObjectName("statusbar")
        UpdateStaffWindow.setStatusBar(self.statusbar)


        self.retranslateUi(UpdateStaffWindow)
        QtCore.QMetaObject.connectSlotsByName(UpdateStaffWindow)



    def retranslateUi(self, UpdateStaffWindow):
        _translate = QtCore.QCoreApplication.translate
        UpdateStaffWindow.setWindowTitle(_translate("UpdateStaffWindow", "MainWindow"))
        self.label_6.setText(_translate("UpdateStaffWindow", "Email"))
        self.label_7.setText(_translate("UpdateStaffWindow", "Salary"))
        self.Updatethestaff.setText(_translate("UpdateStaffWindow", "Update"))
        self.label_4.setText(_translate("UpdateStaffWindow", "User"))
        self.label_3.setText(_translate("UpdateStaffWindow", "Name:"))
        self.label_5.setText(_translate("UpdateStaffWindow", "password"))
        self.label_8.setText(_translate("UpdateStaffWindow", "Update Staff"))
        self.label_12.setText(_translate("UpdateStaffWindow", "Address"))
        self.label_13.setText(_translate("UpdateStaffWindow", "Start Date"))




class Ui_ChnagePsswordWindow(object):
    def setupUi(self, ChnagePsswordWindow):
        ChnagePsswordWindow.setObjectName("ChnagePsswordWindow")
        ChnagePsswordWindow.resize(501, 524)
        ChnagePsswordWindow.setStyleSheet("\n"
"")
        self.centralwidget = QtWidgets.QWidget(ChnagePsswordWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ChnagePasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChnagePasswordButton.setGeometry(QtCore.QRect(120, 390, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.ChnagePasswordButton.setFont(font)
        self.ChnagePasswordButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ChnagePasswordButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.ChnagePasswordButton.setObjectName("ChnagePasswordButton")
        self.NewPassTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.NewPassTXT.setGeometry(QtCore.QRect(260, 60, 171, 41))
        self.NewPassTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.NewPassTXT.setObjectName("NewPassTXT")
        self.CinfirmNewPassTXT = QtWidgets.QLineEdit(self.centralwidget)
        self.CinfirmNewPassTXT.setGeometry(QtCore.QRect(260, 150, 171, 41))
        self.CinfirmNewPassTXT.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.CinfirmNewPassTXT.setObjectName("CinfirmNewPassTXT")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 221, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 241, 41))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.PassDoenstMatchLabel = QtWidgets.QLabel(self.centralwidget)
        self.PassDoenstMatchLabel.setGeometry(QtCore.QRect(20, 280, 471, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(24)
        self.PassDoenstMatchLabel.setFont(font)
        self.PassDoenstMatchLabel.setStyleSheet("color : red")
        self.PassDoenstMatchLabel.setText("")
        self.PassDoenstMatchLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.PassDoenstMatchLabel.setObjectName("PassDoenstMatchLabel")
        ChnagePsswordWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChnagePsswordWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 21))
        self.menubar.setObjectName("menubar")
        ChnagePsswordWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChnagePsswordWindow)
        self.statusbar.setObjectName("statusbar")
        ChnagePsswordWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChnagePsswordWindow)
        QtCore.QMetaObject.connectSlotsByName(ChnagePsswordWindow)

    def retranslateUi(self, ChnagePsswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ChnagePsswordWindow.setWindowTitle(_translate("ChnagePsswordWindow", "Change Password"))
        self.ChnagePasswordButton.setText(_translate("ChnagePsswordWindow", "Chnage Password"))
        self.label_3.setText(_translate("ChnagePsswordWindow", "New Pass"))
        self.label_4.setText(_translate("ChnagePsswordWindow", "Confirm New Pass"))







class Ui_StaffProfileWindow(object):
    def setupUi(self, StaffProfileWindow):
        StaffProfileWindow.setObjectName("StaffProfileWindow")
        StaffProfileWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(StaffProfileWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 791, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.StafeProfileTable = QtWidgets.QTableWidget(self.centralwidget)
        self.StafeProfileTable.setEnabled(False)
        self.StafeProfileTable.setGeometry(QtCore.QRect(50, 90, 721, 371))
        self.StafeProfileTable.setObjectName("StafeProfileTable")
        self.StafeProfileTable.setColumnCount(7)
        self.StafeProfileTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(6, item)
        self.ChnagePasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChnagePasswordButton.setGeometry(QtCore.QRect(540, 480, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.ChnagePasswordButton.setFont(font)
        self.ChnagePasswordButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ChnagePasswordButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.ChnagePasswordButton.setObjectName("ChnagePasswordButton")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(70, 480, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.BackButton.setFont(font)
        self.BackButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BackButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.BackButton.setObjectName("BackButton")
        StaffProfileWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StaffProfileWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        StaffProfileWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StaffProfileWindow)
        self.statusbar.setObjectName("statusbar")
        StaffProfileWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StaffProfileWindow)
        QtCore.QMetaObject.connectSlotsByName(StaffProfileWindow)

    def retranslateUi(self, StaffProfileWindow):
        _translate = QtCore.QCoreApplication.translate
        StaffProfileWindow.setWindowTitle(_translate("StaffProfileWindow", "MainWindow"))
        self.label.setText(_translate("StaffProfileWindow", "Profile"))
        item = self.StafeProfileTable.horizontalHeaderItem(0)
        item.setText(_translate("StaffProfileWindow", "Name"))
        item = self.StafeProfileTable.horizontalHeaderItem(1)
        item.setText(_translate("StaffProfileWindow", "ID Num"))
        item = self.StafeProfileTable.horizontalHeaderItem(2)
        item.setText(_translate("StaffProfileWindow", "Address"))
        item = self.StafeProfileTable.horizontalHeaderItem(3)
        item.setText(_translate("StaffProfileWindow", "Starting Date"))
        item = self.StafeProfileTable.horizontalHeaderItem(4)
        item.setText(_translate("StaffProfileWindow", "Email"))
        item = self.StafeProfileTable.horizontalHeaderItem(5)
        item.setText(_translate("StaffProfileWindow", "User Name"))
        item = self.StafeProfileTable.horizontalHeaderItem(6)
        item.setText(_translate("StaffProfileWindow", "Salary"))
        self.ChnagePasswordButton.setText(_translate("StaffProfileWindow", "Chnage Password"))
        self.BackButton.setText(_translate("StaffProfileWindow", "Back"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    LoginWindow_ui = Ui_LoginWindow()
    LoginWindow_ui.setupUi(LoginWindow)
    LoginWindow.show()
    # sys.exit(app.exec_())

    # app = QtWidgets.QApplication(sys.argv)
    RegisterWindow = QtWidgets.QMainWindow()
    ui = Ui_RegisterWindow()
    ui.setupUi(RegisterWindow)
    # RegisterWindow.show()
    # sys.exit(app.exec_())

    # app = QtWidgets.QApplication(sys.argv)
    CustomerWindow = QtWidgets.QMainWindow()
    CustomerWindow_ui = Ui_CustomerWindow()
    CustomerWindow_ui.setupUi(CustomerWindow)
    # CustomerWindow.show()
    # sys.exit(app.exec_())

    # app = QtWidgets.QApplication(sys.argv)
    adminWindow = QtWidgets.QMainWindow()
    adminWindow_ui = Ui_adminWindow()
    adminWindow_ui.setupUi(adminWindow)
    # adminWindow.show()
    # sys.exit(app.exec_())

    # app = QtWidgets.QApplication(sys.argv)
    AddStaffWIndow = QtWidgets.QMainWindow()
    AddStaffWIndow_ui = Ui_AddStaffWIndow()
    AddStaffWIndow_ui.setupUi(AddStaffWIndow)
    # AddStaffWIndow.show()
    # sys.exit(app.exec_())

    FoodsWindow = QtWidgets.QMainWindow()
    FoodsWindow_ui = Ui_FoodsWindow()
    FoodsWindow_ui.setupUi(FoodsWindow)
    # FoodsWindow.show()
    # sys.exit(app.exec_())

    # app = QtWidgets.QApplication(sys.argv)
    OrdersWindow = QtWidgets.QMainWindow()
    OrdersWindow_ui = Ui_OrdersWindow()
    OrdersWindow_ui.setupUi(OrdersWindow)
    # OrdersWindow.show()
    # sys.exit(app.exec_())

    # app = QtWidgets.QApplication(sys.argv)
    StaffIrderWindow = QtWidgets.QMainWindow()
    StaffIrderWindow_ui = Ui_StaffIrderWindow()
    StaffIrderWindow_ui.setupUi(StaffIrderWindow)
    # StaffIrderWindow.show()
    # sys.exit(app.exec_())

    # app = QtWidgets.QApplication(sys.argv)
    StaffProfileWindow = QtWidgets.QMainWindow()
    StaffProfileWindow_ui = Ui_StaffProfileWindow()
    StaffProfileWindow_ui.setupUi(StaffProfileWindow)
    # StaffProfileWindow.show()
    # sys.exit(app.exec_())

    # app = QtWidgets.QApplication(sys.argv)
    UpdateStaffWindow = QtWidgets.QMainWindow()
    UpdateStaffWindow_ui = Ui_UpdateStaffWindow()
    UpdateStaffWindow_ui.setupUi(UpdateStaffWindow)
    # UpdateStaffWindow.show()
    # sys.exit(app.exec_())


    # app = QtWidgets.QApplication(sys.argv)
    ChnagePsswordWindow = QtWidgets.QMainWindow()
    ChnagePsswordWindow_ui = Ui_ChnagePsswordWindow()
    ChnagePsswordWindow_ui.setupUi(ChnagePsswordWindow)
    # ChnagePsswordWindow.show()
    sys.exit(app.exec_())


