# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OrderforAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrdersWindow(object):

    def setupUi(self, OrdersWindow):
        OrdersWindow.setObjectName("OrdersWindow")
        OrdersWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(OrdersWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OrderTable = QtWidgets.QTableWidget(self.centralwidget)
        self.OrderTable.setGeometry(QtCore.QRect(180, 110, 501, 321))
        self.OrderTable.setObjectName("OrderTable")
        self.OrderTable.setColumnCount(7)
        self.OrderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(6, item)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 10, 441, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.DeleteOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteOrderButton.setGeometry(QtCore.QRect(340, 460, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.DeleteOrderButton.setFont(font)
        self.DeleteOrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DeleteOrderButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.DeleteOrderButton.setObjectName("DeleteOrderButton")
        OrdersWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OrdersWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        OrdersWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OrdersWindow)
        self.statusbar.setObjectName("statusbar")
        OrdersWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OrdersWindow)
        QtCore.QMetaObject.connectSlotsByName(OrdersWindow)

    def retranslateUi(self, OrdersWindow):
        _translate = QtCore.QCoreApplication.translate
        OrdersWindow.setWindowTitle(_translate("OrdersWindow", "MainWindow"))
        item = self.OrderTable.horizontalHeaderItem(0)
        item.setText(_translate("OrdersWindow", "Order ID"))
        item = self.OrderTable.horizontalHeaderItem(1)
        item.setText(_translate("OrdersWindow", "Item Name"))
        item = self.OrderTable.horizontalHeaderItem(2)
        item.setText(_translate("OrdersWindow", "Item Price"))
        item = self.OrderTable.horizontalHeaderItem(3)
        item.setText(_translate("OrdersWindow", "Order Status"))
        item = self.OrderTable.horizontalHeaderItem(4)
        item.setText(_translate("OrdersWindow", "Total Price"))
        self.label_7.setText(_translate("OrdersWindow", "Orders"))
        self.DeleteOrderButton.setText(_translate("OrdersWindow", "Delete Order"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrdersWindow = QtWidgets.QMainWindow()
    ui = Ui_OrdersWindow()
    ui.setupUi(OrdersWindow)
    OrdersWindow.show()
    sys.exit(app.exec_())
