# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StaffProfileMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StaffProfileWindow(object):
    def setupUi(self, StaffProfileWindow):
        StaffProfileWindow.setObjectName("StaffProfileWindow")
        StaffProfileWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(StaffProfileWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 791, 61))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.StafeProfileTable = QtWidgets.QTableWidget(self.centralwidget)
        self.StafeProfileTable.setEnabled(False)
        self.StafeProfileTable.setGeometry(QtCore.QRect(50, 90, 721, 371))
        self.StafeProfileTable.setObjectName("StafeProfileTable")
        self.StafeProfileTable.setColumnCount(7)
        self.StafeProfileTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.StafeProfileTable.setHorizontalHeaderItem(6, item)
        self.ChnagePasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChnagePasswordButton.setGeometry(QtCore.QRect(540, 480, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.ChnagePasswordButton.setFont(font)
        self.ChnagePasswordButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ChnagePasswordButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.ChnagePasswordButton.setObjectName("ChnagePasswordButton")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(70, 480, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.BackButton.setFont(font)
        self.BackButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BackButton.setStyleSheet("background-color: rgb(170, 170, 127)")
        self.BackButton.setObjectName("BackButton")
        StaffProfileWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StaffProfileWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        StaffProfileWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StaffProfileWindow)
        self.statusbar.setObjectName("statusbar")
        StaffProfileWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StaffProfileWindow)
        QtCore.QMetaObject.connectSlotsByName(StaffProfileWindow)

    def retranslateUi(self, StaffProfileWindow):
        _translate = QtCore.QCoreApplication.translate
        StaffProfileWindow.setWindowTitle(_translate("StaffProfileWindow", "MainWindow"))
        self.label.setText(_translate("StaffProfileWindow", "Profile"))
        item = self.StafeProfileTable.horizontalHeaderItem(0)
        item.setText(_translate("StaffProfileWindow", "Name"))
        item = self.StafeProfileTable.horizontalHeaderItem(1)
        item.setText(_translate("StaffProfileWindow", "ID Num"))
        item = self.StafeProfileTable.horizontalHeaderItem(2)
        item.setText(_translate("StaffProfileWindow", "Address"))
        item = self.StafeProfileTable.horizontalHeaderItem(3)
        item.setText(_translate("StaffProfileWindow", "Starting Date"))
        item = self.StafeProfileTable.horizontalHeaderItem(4)
        item.setText(_translate("StaffProfileWindow", "Email"))
        item = self.StafeProfileTable.horizontalHeaderItem(5)
        item.setText(_translate("StaffProfileWindow", "User Name"))
        item = self.StafeProfileTable.horizontalHeaderItem(6)
        item.setText(_translate("StaffProfileWindow", "Salary"))
        self.ChnagePasswordButton.setText(_translate("StaffProfileWindow", "Chnage Password"))
        self.BackButton.setText(_translate("StaffProfileWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StaffProfileWindow = QtWidgets.QMainWindow()
    ui = Ui_StaffProfileWindow()
    ui.setupUi(StaffProfileWindow)
    StaffProfileWindow.show()
    sys.exit(app.exec_())
